[package]
name = "rast_basics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.21.1"
clap = { version = "3.2.5", features = ["derive"] }
regex = "1.6.0"
rand = "0.8.5"
